### ISSUE TITLE
Data Extracts

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#147]
Provide standard naming convention for downloaded reports.  
i.e. unit_report or form name_date generated

Also if on columns that are "last modified" or "due in" could just be numbers (instead of "due in 30 days" or "2 months ago") so that sorting could be performed easily once downloaded

![image](https://user-images.githubusercontent.com/29133992/28322885-49818efc-6ba5-11e7-910d-2086b188f76d.png)

**Comment by mattgwagner** [comment]
I need to look at the Javascript plugin that's used to generate the export formats and see how to show/hide columns when exporting... I also want to hide the buttons. I fixed it so that the sorting works properly on the HTML version, but would make sense to also make Excel usable.

REF: https://datatables.net/extensions/buttons/examples/initialisation/export

**Comment by mattgwagner** [comment]
Export for Excel and CSV will now use the 'sort' orthogonal data.

![image](https://user-images.githubusercontent.com/157644/28327631-fd0d1dfe-6bb1-11e7-94e0-a00232ca0428.png)

Still need to do a filename convention.

**Comment by mattgwagner** [comment]
I can't do unit name since it's not in the scope of view (wasn't built to only show one unit). However, I updated it to include the report name and generated time.

![image](https://user-images.githubusercontent.com/157644/28374781-c01cb9f0-6c73-11e7-8417-69c6f6972b72.png)
