### ISSUE TITLE
Evaluations delinquency counter

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#177]
Delinquency counter should stop once workflow equals "submitted to HQDA"

**Comment by erichmccartney** [comment]
Then i suppose it would need to re-start if it gets returned, oh my all these implications.

**Comment by mattgwagner** [comment]
Agreed on the implications part... since it's still technically delinquent X number of days, even if you've submitted once or twice only to have it kicked back. Otherwise, I'd have to go back through events and check for "submitted", but I'm technically not storing the event/status, just the human-readable note.
