### ISSUE TITLE
Soldier add conflict

### ISSUE THREAD

**Issue by erichmccartney** [mattgwagner/Battery-Commander#377]
As new users are using the system they are attempting to add soldiers that may already exist in the db.  is a fuzzy look up and conflict detection available to remove the ability for a duplicate profile to be added? 

Apparently last night the new guy at the DLD added me then realized I already existed and he deleted me.  If all that is true, kinda concerning that a record can be deleted that easy.

More users are definitely more problems

**Comment by mattgwagner** [comment]
I added some additional checks to call out duplicate first/last names. The database already had a key to prevent first/middle/last or dod ids matching, because I know we had two SMs in a previous unit with the same first/last. There's a "force" button on the form to force creating a new Soldier.

![image](https://user-images.githubusercontent.com/157644/52885415-2aaa1100-313f-11e9-9521-20e9a517d78d.png)


![image](https://user-images.githubusercontent.com/157644/52885412-1fef7c00-313f-11e9-9a3c-6304401ee11b.png)
